SUMMON_ICE_TROLL_TO_KILL_ELF_RANGE_FROM_ENEMY_ELF = 1000;
SUMMON_LAVA_GIANT_RANGE_FROM_CASTLE = 2000;
RANGE_TO_EVASE = 750;
RANGE_OF_MY_ICE_TROLL_TO_ENEMY_TO_ATTACK = 500;
RANGE_ENEMY_TO_MY_CASTLE_TO_DEFEND = 3000;
DEFENSE_PORTAL_RANGE_FROM_MY_CASTLE = 2000;
MIN_MANA_TO_BUILD_PORTAL = 149;
MIN_MANA_TO_SUMMON_CREATURE = 89;
